spring.application.name=refund-chargeback-service
server.port=8085

spring.datasource.url=jdbc:mysql://localhost:3306/refund_chargeback_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

refund.merchant.default-threshold=1000.00
